version: '2'
services:
    selective-app:
        image: selective
        external_links:
            - selective-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/selective?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    selective-mysql:
        extends:
            file: mysql.yml
            service: selective-mysql
